apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: residencias
        image: docker.io/library/residencias:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
