apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"  # Cambia la contraseña de root
        - name: MYSQL_DATABASE
          value: "testdb"  # Nombre de la base de datos
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "userpassword"  # Cambia la contraseña del usuario
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
